/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as AppRouteImport } from './routes/app'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as PathlessLayoutBRouteImport } from './routes/_pathlessLayout.b'
import { Route as PathlessLayoutARouteImport } from './routes/_pathlessLayout.a'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as publicSearchRouteRouteImport } from './routes/(public)/search/route'
import { Route as publicCategoriesRouteRouteImport } from './routes/(public)/categories/route'
import { Route as publicContactUsIndexRouteImport } from './routes/(public)/contact-us/index'
import { Route as PostsIdEditRouteImport } from './routes/posts_.$id.edit'
import { Route as PostsChar123CategoryChar125Char123SlugChar125RouteImport } from './routes/posts/{-$category}.{-$slug}'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DashboardLayoutSettingRouteImport } from './routes/dashboard/_layout.setting'
import { Route as DashboardLayoutAboutRouteImport } from './routes/dashboard/_layout.about'
import { Route as publicContactUsCountryRouteImport } from './routes/(public)/contact-us/$country'
import { Route as publicCategoriesCategoryIdRouteRouteImport } from './routes/(public)/categories/$categoryId/route'
import { Route as publicContactUsCountryCityRouteImport } from './routes/(public)/contact-us/$country.$city'
import { Route as publicCategoriesCategoryIdSubcategoryIdRouteRouteImport } from './routes/(public)/categories/$categoryId/$subcategoryId/route'
import { Route as publicAppUsersUserIdRouteRouteImport } from './routes/(public)/app/users/$userId.route'
import { Route as publicAppUsersUserIdSettingRouteImport } from './routes/(public)/app/users/$userId.setting'
import { Route as publicAppUsersUserIdEditRouteImport } from './routes/(public)/app/users/$userId.edit'
import { Route as publicCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport } from './routes/(public)/categories/$categoryId/$subcategoryId/$productId/route'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostsRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutBRoute = PathlessLayoutBRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutARoute = PathlessLayoutARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSearchRouteRoute = publicSearchRouteRouteImport.update({
  id: '/(public)/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCategoriesRouteRoute = publicCategoriesRouteRouteImport.update({
  id: '/(public)/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const publicContactUsIndexRoute = publicContactUsIndexRouteImport.update({
  id: '/(public)/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdEditRoute = PostsIdEditRouteImport.update({
  id: '/posts_/$id/edit',
  path: '/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsChar123CategoryChar125Char123SlugChar125Route =
  PostsChar123CategoryChar125Char123SlugChar125RouteImport.update({
    id: '/{-$category}/{-$slug}',
    path: '/{-$category}/{-$slug}',
    getParentRoute: () => PostsRoute,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutSettingRoute = DashboardLayoutSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutAboutRoute = DashboardLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const publicContactUsCountryRoute = publicContactUsCountryRouteImport.update({
  id: '/(public)/contact-us/$country',
  path: '/contact-us/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCategoriesCategoryIdRouteRoute =
  publicCategoriesCategoryIdRouteRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => publicCategoriesRouteRoute,
  } as any)
const publicContactUsCountryCityRoute =
  publicContactUsCountryCityRouteImport.update({
    id: '/$city',
    path: '/$city',
    getParentRoute: () => publicContactUsCountryRoute,
  } as any)
const publicCategoriesCategoryIdSubcategoryIdRouteRoute =
  publicCategoriesCategoryIdSubcategoryIdRouteRouteImport.update({
    id: '/$subcategoryId',
    path: '/$subcategoryId',
    getParentRoute: () => publicCategoriesCategoryIdRouteRoute,
  } as any)
const publicAppUsersUserIdRouteRoute =
  publicAppUsersUserIdRouteRouteImport.update({
    id: '/(public)/app/users/$userId',
    path: '/app/users/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicAppUsersUserIdSettingRoute =
  publicAppUsersUserIdSettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => publicAppUsersUserIdRouteRoute,
  } as any)
const publicAppUsersUserIdEditRoute =
  publicAppUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => publicAppUsersUserIdRouteRoute,
  } as any)
const publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute =
  publicCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => publicCategoriesCategoryIdSubcategoryIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/posts': typeof PostsRouteWithChildren
  '/categories': typeof publicCategoriesRouteRouteWithChildren
  '/search': typeof publicSearchRouteRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/a': typeof PathlessLayoutARoute
  '/b': typeof PathlessLayoutBRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/posts/$id': typeof PostsIdRoute
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRouteWithChildren
  '/contact-us/$country': typeof publicContactUsCountryRouteWithChildren
  '/dashboard/about': typeof DashboardLayoutAboutRoute
  '/dashboard/setting': typeof DashboardLayoutSettingRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/posts/{-$category}/{-$slug}': typeof PostsChar123CategoryChar125Char123SlugChar125Route
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/contact-us/': typeof publicContactUsIndexRoute
  '/app/users/$userId': typeof publicAppUsersUserIdRouteRouteWithChildren
  '/categories/$categoryId/$subcategoryId': typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof publicContactUsCountryCityRoute
  '/categories/$categoryId/$subcategoryId/$productId': typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/app/users/$userId/edit': typeof publicAppUsersUserIdEditRoute
  '/app/users/$userId/setting': typeof publicAppUsersUserIdSettingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/posts': typeof PostsRouteWithChildren
  '/categories': typeof publicCategoriesRouteRouteWithChildren
  '/search': typeof publicSearchRouteRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/a': typeof PathlessLayoutARoute
  '/b': typeof PathlessLayoutBRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/posts/$id': typeof PostsIdRoute
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRouteWithChildren
  '/contact-us/$country': typeof publicContactUsCountryRouteWithChildren
  '/dashboard/about': typeof DashboardLayoutAboutRoute
  '/dashboard/setting': typeof DashboardLayoutSettingRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/posts/{-$category}/{-$slug}': typeof PostsChar123CategoryChar125Char123SlugChar125Route
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/contact-us': typeof publicContactUsIndexRoute
  '/app/users/$userId': typeof publicAppUsersUserIdRouteRouteWithChildren
  '/categories/$categoryId/$subcategoryId': typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof publicContactUsCountryCityRoute
  '/categories/$categoryId/$subcategoryId/$productId': typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/app/users/$userId/edit': typeof publicAppUsersUserIdEditRoute
  '/app/users/$userId/setting': typeof publicAppUsersUserIdSettingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/app': typeof AppRoute
  '/posts': typeof PostsRouteWithChildren
  '/(public)/categories': typeof publicCategoriesRouteRouteWithChildren
  '/(public)/search': typeof publicSearchRouteRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_pathlessLayout/a': typeof PathlessLayoutARoute
  '/_pathlessLayout/b': typeof PathlessLayoutBRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/posts/$id': typeof PostsIdRoute
  '/(public)/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRouteWithChildren
  '/(public)/contact-us/$country': typeof publicContactUsCountryRouteWithChildren
  '/dashboard/_layout/about': typeof DashboardLayoutAboutRoute
  '/dashboard/_layout/setting': typeof DashboardLayoutSettingRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/posts/{-$category}/{-$slug}': typeof PostsChar123CategoryChar125Char123SlugChar125Route
  '/posts_/$id/edit': typeof PostsIdEditRoute
  '/(public)/contact-us/': typeof publicContactUsIndexRoute
  '/(public)/app/users/$userId': typeof publicAppUsersUserIdRouteRouteWithChildren
  '/(public)/categories/$categoryId/$subcategoryId': typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/(public)/contact-us/$country/$city': typeof publicContactUsCountryCityRoute
  '/(public)/categories/$categoryId/$subcategoryId/$productId': typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/(public)/app/users/$userId/edit': typeof publicAppUsersUserIdEditRoute
  '/(public)/app/users/$userId/setting': typeof publicAppUsersUserIdSettingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/posts'
    | '/categories'
    | '/search'
    | '/login'
    | '/register'
    | '/a'
    | '/b'
    | '/dashboard'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/posts/$id'
    | '/categories/$categoryId'
    | '/contact-us/$country'
    | '/dashboard/about'
    | '/dashboard/setting'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/posts/{-$category}/{-$slug}'
    | '/posts/$id/edit'
    | '/contact-us/'
    | '/app/users/$userId'
    | '/categories/$categoryId/$subcategoryId'
    | '/contact-us/$country/$city'
    | '/categories/$categoryId/$subcategoryId/$productId'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/posts'
    | '/categories'
    | '/search'
    | '/login'
    | '/register'
    | '/a'
    | '/b'
    | '/dashboard'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/posts/$id'
    | '/categories/$categoryId'
    | '/contact-us/$country'
    | '/dashboard/about'
    | '/dashboard/setting'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/posts/{-$category}/{-$slug}'
    | '/posts/$id/edit'
    | '/contact-us'
    | '/app/users/$userId'
    | '/categories/$categoryId/$subcategoryId'
    | '/contact-us/$country/$city'
    | '/categories/$categoryId/$subcategoryId/$productId'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/setting'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/app'
    | '/posts'
    | '/(public)/categories'
    | '/(public)/search'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_pathlessLayout/a'
    | '/_pathlessLayout/b'
    | '/dashboard/_layout'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/posts/$id'
    | '/(public)/categories/$categoryId'
    | '/(public)/contact-us/$country'
    | '/dashboard/_layout/about'
    | '/dashboard/_layout/setting'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/posts/{-$category}/{-$slug}'
    | '/posts_/$id/edit'
    | '/(public)/contact-us/'
    | '/(public)/app/users/$userId'
    | '/(public)/categories/$categoryId/$subcategoryId'
    | '/(public)/contact-us/$country/$city'
    | '/(public)/categories/$categoryId/$subcategoryId/$productId'
    | '/(public)/app/users/$userId/edit'
    | '/(public)/app/users/$userId/setting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AppRoute: typeof AppRoute
  PostsRoute: typeof PostsRouteWithChildren
  publicCategoriesRouteRoute: typeof publicCategoriesRouteRouteWithChildren
  publicSearchRouteRoute: typeof publicSearchRouteRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  publicContactUsCountryRoute: typeof publicContactUsCountryRouteWithChildren
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  PostsIdEditRoute: typeof PostsIdEditRoute
  publicContactUsIndexRoute: typeof publicContactUsIndexRoute
  publicAppUsersUserIdRouteRoute: typeof publicAppUsersUserIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/b': {
      id: '/_pathlessLayout/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof PathlessLayoutBRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/a': {
      id: '/_pathlessLayout/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof PathlessLayoutARouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/search': {
      id: '/(public)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof publicSearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/categories': {
      id: '/(public)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof publicCategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/contact-us/': {
      id: '/(public)/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof publicContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$id/edit': {
      id: '/posts_/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/posts/$id/edit'
      preLoaderRoute: typeof PostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/{-$category}/{-$slug}': {
      id: '/posts/{-$category}/{-$slug}'
      path: '/{-$category}/{-$slug}'
      fullPath: '/posts/{-$category}/{-$slug}'
      preLoaderRoute: typeof PostsChar123CategoryChar125Char123SlugChar125RouteImport
      parentRoute: typeof PostsRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/setting': {
      id: '/dashboard/_layout/setting'
      path: '/setting'
      fullPath: '/dashboard/setting'
      preLoaderRoute: typeof DashboardLayoutSettingRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/about': {
      id: '/dashboard/_layout/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardLayoutAboutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/(public)/contact-us/$country': {
      id: '/(public)/contact-us/$country'
      path: '/contact-us/$country'
      fullPath: '/contact-us/$country'
      preLoaderRoute: typeof publicContactUsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/categories/$categoryId': {
      id: '/(public)/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof publicCategoriesCategoryIdRouteRouteImport
      parentRoute: typeof publicCategoriesRouteRoute
    }
    '/(public)/contact-us/$country/$city': {
      id: '/(public)/contact-us/$country/$city'
      path: '/$city'
      fullPath: '/contact-us/$country/$city'
      preLoaderRoute: typeof publicContactUsCountryCityRouteImport
      parentRoute: typeof publicContactUsCountryRoute
    }
    '/(public)/categories/$categoryId/$subcategoryId': {
      id: '/(public)/categories/$categoryId/$subcategoryId'
      path: '/$subcategoryId'
      fullPath: '/categories/$categoryId/$subcategoryId'
      preLoaderRoute: typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteImport
      parentRoute: typeof publicCategoriesCategoryIdRouteRoute
    }
    '/(public)/app/users/$userId': {
      id: '/(public)/app/users/$userId'
      path: '/app/users/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof publicAppUsersUserIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/app/users/$userId/setting': {
      id: '/(public)/app/users/$userId/setting'
      path: '/setting'
      fullPath: '/app/users/$userId/setting'
      preLoaderRoute: typeof publicAppUsersUserIdSettingRouteImport
      parentRoute: typeof publicAppUsersUserIdRouteRoute
    }
    '/(public)/app/users/$userId/edit': {
      id: '/(public)/app/users/$userId/edit'
      path: '/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof publicAppUsersUserIdEditRouteImport
      parentRoute: typeof publicAppUsersUserIdRouteRoute
    }
    '/(public)/categories/$categoryId/$subcategoryId/$productId': {
      id: '/(public)/categories/$categoryId/$subcategoryId/$productId'
      path: '/$productId'
      fullPath: '/categories/$categoryId/$subcategoryId/$productId'
      preLoaderRoute: typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport
      parentRoute: typeof publicCategoriesCategoryIdSubcategoryIdRouteRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutARoute: typeof PathlessLayoutARoute
  PathlessLayoutBRoute: typeof PathlessLayoutBRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutARoute: PathlessLayoutARoute,
  PathlessLayoutBRoute: PathlessLayoutBRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsIdRoute: typeof PostsIdRoute
  PostsChar123CategoryChar125Char123SlugChar125Route: typeof PostsChar123CategoryChar125Char123SlugChar125Route
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsIdRoute: PostsIdRoute,
  PostsChar123CategoryChar125Char123SlugChar125Route:
    PostsChar123CategoryChar125Char123SlugChar125Route,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren {
  publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute: typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
}

const publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren: publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren =
  {
    publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute:
      publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute,
  }

const publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren =
  publicCategoriesCategoryIdSubcategoryIdRouteRoute._addFileChildren(
    publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren,
  )

interface publicCategoriesCategoryIdRouteRouteChildren {
  publicCategoriesCategoryIdSubcategoryIdRouteRoute: typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
}

const publicCategoriesCategoryIdRouteRouteChildren: publicCategoriesCategoryIdRouteRouteChildren =
  {
    publicCategoriesCategoryIdSubcategoryIdRouteRoute:
      publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren,
  }

const publicCategoriesCategoryIdRouteRouteWithChildren =
  publicCategoriesCategoryIdRouteRoute._addFileChildren(
    publicCategoriesCategoryIdRouteRouteChildren,
  )

interface publicCategoriesRouteRouteChildren {
  publicCategoriesCategoryIdRouteRoute: typeof publicCategoriesCategoryIdRouteRouteWithChildren
}

const publicCategoriesRouteRouteChildren: publicCategoriesRouteRouteChildren = {
  publicCategoriesCategoryIdRouteRoute:
    publicCategoriesCategoryIdRouteRouteWithChildren,
}

const publicCategoriesRouteRouteWithChildren =
  publicCategoriesRouteRoute._addFileChildren(
    publicCategoriesRouteRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutAboutRoute: typeof DashboardLayoutAboutRoute
  DashboardLayoutSettingRoute: typeof DashboardLayoutSettingRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutAboutRoute: DashboardLayoutAboutRoute,
  DashboardLayoutSettingRoute: DashboardLayoutSettingRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface publicContactUsCountryRouteChildren {
  publicContactUsCountryCityRoute: typeof publicContactUsCountryCityRoute
}

const publicContactUsCountryRouteChildren: publicContactUsCountryRouteChildren =
  {
    publicContactUsCountryCityRoute: publicContactUsCountryCityRoute,
  }

const publicContactUsCountryRouteWithChildren =
  publicContactUsCountryRoute._addFileChildren(
    publicContactUsCountryRouteChildren,
  )

interface publicAppUsersUserIdRouteRouteChildren {
  publicAppUsersUserIdEditRoute: typeof publicAppUsersUserIdEditRoute
  publicAppUsersUserIdSettingRoute: typeof publicAppUsersUserIdSettingRoute
}

const publicAppUsersUserIdRouteRouteChildren: publicAppUsersUserIdRouteRouteChildren =
  {
    publicAppUsersUserIdEditRoute: publicAppUsersUserIdEditRoute,
    publicAppUsersUserIdSettingRoute: publicAppUsersUserIdSettingRoute,
  }

const publicAppUsersUserIdRouteRouteWithChildren =
  publicAppUsersUserIdRouteRoute._addFileChildren(
    publicAppUsersUserIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AppRoute: AppRoute,
  PostsRoute: PostsRouteWithChildren,
  publicCategoriesRouteRoute: publicCategoriesRouteRouteWithChildren,
  publicSearchRouteRoute: publicSearchRouteRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  publicContactUsCountryRoute: publicContactUsCountryRouteWithChildren,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  PostsIdEditRoute: PostsIdEditRoute,
  publicContactUsIndexRoute: publicContactUsIndexRoute,
  publicAppUsersUserIdRouteRoute: publicAppUsersUserIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
