/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayDisplayRouteImport } from './routes/display/Display'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ClientClientLayoutRouteRouteImport } from './routes/client/_clientLayout/route'
import { Route as AdminAdminLayoutRouteRouteImport } from './routes/admin/_adminLayout/route'
import { Route as DashboardLayoutSettingRouteImport } from './routes/dashboard/_layout.setting'
import { Route as DashboardLayoutAboutRouteImport } from './routes/dashboard/_layout.about'
import { Route as ClientClientLayoutDashboardRouteRouteImport } from './routes/client/_clientLayout/dashboard/route'
import { Route as AdminAdminLayoutSearchRouteRouteImport } from './routes/admin/_adminLayout/search/route'
import { Route as AdminAdminLayoutDashboardRouteRouteImport } from './routes/admin/_adminLayout/dashboard/route'
import { Route as AdminAdminLayoutCategoriesRouteRouteImport } from './routes/admin/_adminLayout/categories/route'
import { Route as ClientClientLayoutContactUsIndexRouteImport } from './routes/client/_clientLayout/contact-us/index'
import { Route as ClientClientLayoutContactUsCountryRouteImport } from './routes/client/_clientLayout/contact-us/$country'
import { Route as AdminAdminLayoutCategoriesCategoryIdRouteRouteImport } from './routes/admin/_adminLayout/categories/$categoryId/route'
import { Route as publicAppUsersUserIdRouteRouteImport } from './routes/(public)/app/users/$userId.route'
import { Route as ClientClientLayoutContactUsCountryCityRouteImport } from './routes/client/_clientLayout/contact-us/$country.$city'
import { Route as publicAppUsersUserIdSettingRouteImport } from './routes/(public)/app/users/$userId.setting'
import { Route as publicAppUsersUserIdEditRouteImport } from './routes/(public)/app/users/$userId.edit'
import { Route as AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteImport } from './routes/admin/_adminLayout/categories/$categoryId/$subcategoryId/route'
import { Route as AdminAdminLayoutAppUsersUserIdRouteRouteImport } from './routes/admin/_adminLayout/app/users/$userId.route'
import { Route as AdminAdminLayoutAppUsersUserIdSettingRouteImport } from './routes/admin/_adminLayout/app/users/$userId.setting'
import { Route as AdminAdminLayoutAppUsersUserIdEditRouteImport } from './routes/admin/_adminLayout/app/users/$userId.edit'
import { Route as AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport } from './routes/admin/_adminLayout/categories/$categoryId/$subcategoryId/$productId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayDisplayRoute = DisplayDisplayRouteImport.update({
  id: '/display/Display',
  path: '/display/Display',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClientLayoutRouteRoute = ClientClientLayoutRouteRouteImport.update({
  id: '/client/_clientLayout',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLayoutRouteRoute = AdminAdminLayoutRouteRouteImport.update({
  id: '/admin/_adminLayout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutSettingRoute = DashboardLayoutSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutAboutRoute = DashboardLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ClientClientLayoutDashboardRouteRoute =
  ClientClientLayoutDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ClientClientLayoutRouteRoute,
  } as any)
const AdminAdminLayoutSearchRouteRoute =
  AdminAdminLayoutSearchRouteRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AdminAdminLayoutRouteRoute,
  } as any)
const AdminAdminLayoutDashboardRouteRoute =
  AdminAdminLayoutDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminAdminLayoutRouteRoute,
  } as any)
const AdminAdminLayoutCategoriesRouteRoute =
  AdminAdminLayoutCategoriesRouteRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminAdminLayoutRouteRoute,
  } as any)
const ClientClientLayoutContactUsIndexRoute =
  ClientClientLayoutContactUsIndexRouteImport.update({
    id: '/contact-us/',
    path: '/contact-us/',
    getParentRoute: () => ClientClientLayoutRouteRoute,
  } as any)
const ClientClientLayoutContactUsCountryRoute =
  ClientClientLayoutContactUsCountryRouteImport.update({
    id: '/contact-us/$country',
    path: '/contact-us/$country',
    getParentRoute: () => ClientClientLayoutRouteRoute,
  } as any)
const AdminAdminLayoutCategoriesCategoryIdRouteRoute =
  AdminAdminLayoutCategoriesCategoryIdRouteRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AdminAdminLayoutCategoriesRouteRoute,
  } as any)
const publicAppUsersUserIdRouteRoute =
  publicAppUsersUserIdRouteRouteImport.update({
    id: '/(public)/app/users/$userId',
    path: '/app/users/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientClientLayoutContactUsCountryCityRoute =
  ClientClientLayoutContactUsCountryCityRouteImport.update({
    id: '/$city',
    path: '/$city',
    getParentRoute: () => ClientClientLayoutContactUsCountryRoute,
  } as any)
const publicAppUsersUserIdSettingRoute =
  publicAppUsersUserIdSettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => publicAppUsersUserIdRouteRoute,
  } as any)
const publicAppUsersUserIdEditRoute =
  publicAppUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => publicAppUsersUserIdRouteRoute,
  } as any)
const AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRoute =
  AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteImport.update({
    id: '/$subcategoryId',
    path: '/$subcategoryId',
    getParentRoute: () => AdminAdminLayoutCategoriesCategoryIdRouteRoute,
  } as any)
const AdminAdminLayoutAppUsersUserIdRouteRoute =
  AdminAdminLayoutAppUsersUserIdRouteRouteImport.update({
    id: '/app/users/$userId',
    path: '/app/users/$userId',
    getParentRoute: () => AdminAdminLayoutRouteRoute,
  } as any)
const AdminAdminLayoutAppUsersUserIdSettingRoute =
  AdminAdminLayoutAppUsersUserIdSettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => AdminAdminLayoutAppUsersUserIdRouteRoute,
  } as any)
const AdminAdminLayoutAppUsersUserIdEditRoute =
  AdminAdminLayoutAppUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminAdminLayoutAppUsersUserIdRouteRoute,
  } as any)
const AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute =
  AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport.update(
    {
      id: '/$productId',
      path: '/$productId',
      getParentRoute: () =>
        AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminLayoutRouteRouteWithChildren
  '/client': typeof ClientClientLayoutRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/display/Display': typeof DisplayDisplayRoute
  '/admin/categories': typeof AdminAdminLayoutCategoriesRouteRouteWithChildren
  '/admin/dashboard': typeof AdminAdminLayoutDashboardRouteRoute
  '/admin/search': typeof AdminAdminLayoutSearchRouteRoute
  '/client/dashboard': typeof ClientClientLayoutDashboardRouteRoute
  '/dashboard/about': typeof DashboardLayoutAboutRoute
  '/dashboard/setting': typeof DashboardLayoutSettingRoute
  '/app/users/$userId': typeof publicAppUsersUserIdRouteRouteWithChildren
  '/admin/categories/$categoryId': typeof AdminAdminLayoutCategoriesCategoryIdRouteRouteWithChildren
  '/client/contact-us/$country': typeof ClientClientLayoutContactUsCountryRouteWithChildren
  '/client/contact-us/': typeof ClientClientLayoutContactUsIndexRoute
  '/admin/app/users/$userId': typeof AdminAdminLayoutAppUsersUserIdRouteRouteWithChildren
  '/admin/categories/$categoryId/$subcategoryId': typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/app/users/$userId/edit': typeof publicAppUsersUserIdEditRoute
  '/app/users/$userId/setting': typeof publicAppUsersUserIdSettingRoute
  '/client/contact-us/$country/$city': typeof ClientClientLayoutContactUsCountryCityRoute
  '/admin/categories/$categoryId/$subcategoryId/$productId': typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/admin/app/users/$userId/edit': typeof AdminAdminLayoutAppUsersUserIdEditRoute
  '/admin/app/users/$userId/setting': typeof AdminAdminLayoutAppUsersUserIdSettingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminLayoutRouteRouteWithChildren
  '/client': typeof ClientClientLayoutRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/display/Display': typeof DisplayDisplayRoute
  '/admin/categories': typeof AdminAdminLayoutCategoriesRouteRouteWithChildren
  '/admin/dashboard': typeof AdminAdminLayoutDashboardRouteRoute
  '/admin/search': typeof AdminAdminLayoutSearchRouteRoute
  '/client/dashboard': typeof ClientClientLayoutDashboardRouteRoute
  '/dashboard/about': typeof DashboardLayoutAboutRoute
  '/dashboard/setting': typeof DashboardLayoutSettingRoute
  '/app/users/$userId': typeof publicAppUsersUserIdRouteRouteWithChildren
  '/admin/categories/$categoryId': typeof AdminAdminLayoutCategoriesCategoryIdRouteRouteWithChildren
  '/client/contact-us/$country': typeof ClientClientLayoutContactUsCountryRouteWithChildren
  '/client/contact-us': typeof ClientClientLayoutContactUsIndexRoute
  '/admin/app/users/$userId': typeof AdminAdminLayoutAppUsersUserIdRouteRouteWithChildren
  '/admin/categories/$categoryId/$subcategoryId': typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/app/users/$userId/edit': typeof publicAppUsersUserIdEditRoute
  '/app/users/$userId/setting': typeof publicAppUsersUserIdSettingRoute
  '/client/contact-us/$country/$city': typeof ClientClientLayoutContactUsCountryCityRoute
  '/admin/categories/$categoryId/$subcategoryId/$productId': typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/admin/app/users/$userId/edit': typeof AdminAdminLayoutAppUsersUserIdEditRoute
  '/admin/app/users/$userId/setting': typeof AdminAdminLayoutAppUsersUserIdSettingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_adminLayout': typeof AdminAdminLayoutRouteRouteWithChildren
  '/client/_clientLayout': typeof ClientClientLayoutRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/display/Display': typeof DisplayDisplayRoute
  '/admin/_adminLayout/categories': typeof AdminAdminLayoutCategoriesRouteRouteWithChildren
  '/admin/_adminLayout/dashboard': typeof AdminAdminLayoutDashboardRouteRoute
  '/admin/_adminLayout/search': typeof AdminAdminLayoutSearchRouteRoute
  '/client/_clientLayout/dashboard': typeof ClientClientLayoutDashboardRouteRoute
  '/dashboard/_layout/about': typeof DashboardLayoutAboutRoute
  '/dashboard/_layout/setting': typeof DashboardLayoutSettingRoute
  '/(public)/app/users/$userId': typeof publicAppUsersUserIdRouteRouteWithChildren
  '/admin/_adminLayout/categories/$categoryId': typeof AdminAdminLayoutCategoriesCategoryIdRouteRouteWithChildren
  '/client/_clientLayout/contact-us/$country': typeof ClientClientLayoutContactUsCountryRouteWithChildren
  '/client/_clientLayout/contact-us/': typeof ClientClientLayoutContactUsIndexRoute
  '/admin/_adminLayout/app/users/$userId': typeof AdminAdminLayoutAppUsersUserIdRouteRouteWithChildren
  '/admin/_adminLayout/categories/$categoryId/$subcategoryId': typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/(public)/app/users/$userId/edit': typeof publicAppUsersUserIdEditRoute
  '/(public)/app/users/$userId/setting': typeof publicAppUsersUserIdSettingRoute
  '/client/_clientLayout/contact-us/$country/$city': typeof ClientClientLayoutContactUsCountryCityRoute
  '/admin/_adminLayout/categories/$categoryId/$subcategoryId/$productId': typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
  '/admin/_adminLayout/app/users/$userId/edit': typeof AdminAdminLayoutAppUsersUserIdEditRoute
  '/admin/_adminLayout/app/users/$userId/setting': typeof AdminAdminLayoutAppUsersUserIdSettingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/dashboard'
    | '/display/Display'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/search'
    | '/client/dashboard'
    | '/dashboard/about'
    | '/dashboard/setting'
    | '/app/users/$userId'
    | '/admin/categories/$categoryId'
    | '/client/contact-us/$country'
    | '/client/contact-us/'
    | '/admin/app/users/$userId'
    | '/admin/categories/$categoryId/$subcategoryId'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/setting'
    | '/client/contact-us/$country/$city'
    | '/admin/categories/$categoryId/$subcategoryId/$productId'
    | '/admin/app/users/$userId/edit'
    | '/admin/app/users/$userId/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/dashboard'
    | '/display/Display'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/search'
    | '/client/dashboard'
    | '/dashboard/about'
    | '/dashboard/setting'
    | '/app/users/$userId'
    | '/admin/categories/$categoryId'
    | '/client/contact-us/$country'
    | '/client/contact-us'
    | '/admin/app/users/$userId'
    | '/admin/categories/$categoryId/$subcategoryId'
    | '/app/users/$userId/edit'
    | '/app/users/$userId/setting'
    | '/client/contact-us/$country/$city'
    | '/admin/categories/$categoryId/$subcategoryId/$productId'
    | '/admin/app/users/$userId/edit'
    | '/admin/app/users/$userId/setting'
  id:
    | '__root__'
    | '/'
    | '/admin/_adminLayout'
    | '/client/_clientLayout'
    | '/(auth)/login'
    | '/dashboard/_layout'
    | '/display/Display'
    | '/admin/_adminLayout/categories'
    | '/admin/_adminLayout/dashboard'
    | '/admin/_adminLayout/search'
    | '/client/_clientLayout/dashboard'
    | '/dashboard/_layout/about'
    | '/dashboard/_layout/setting'
    | '/(public)/app/users/$userId'
    | '/admin/_adminLayout/categories/$categoryId'
    | '/client/_clientLayout/contact-us/$country'
    | '/client/_clientLayout/contact-us/'
    | '/admin/_adminLayout/app/users/$userId'
    | '/admin/_adminLayout/categories/$categoryId/$subcategoryId'
    | '/(public)/app/users/$userId/edit'
    | '/(public)/app/users/$userId/setting'
    | '/client/_clientLayout/contact-us/$country/$city'
    | '/admin/_adminLayout/categories/$categoryId/$subcategoryId/$productId'
    | '/admin/_adminLayout/app/users/$userId/edit'
    | '/admin/_adminLayout/app/users/$userId/setting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAdminLayoutRouteRoute: typeof AdminAdminLayoutRouteRouteWithChildren
  ClientClientLayoutRouteRoute: typeof ClientClientLayoutRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DisplayDisplayRoute: typeof DisplayDisplayRoute
  publicAppUsersUserIdRouteRoute: typeof publicAppUsersUserIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/Display': {
      id: '/display/Display'
      path: '/display/Display'
      fullPath: '/display/Display'
      preLoaderRoute: typeof DisplayDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/_clientLayout': {
      id: '/client/_clientLayout'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientClientLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_adminLayout': {
      id: '/admin/_adminLayout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/setting': {
      id: '/dashboard/_layout/setting'
      path: '/setting'
      fullPath: '/dashboard/setting'
      preLoaderRoute: typeof DashboardLayoutSettingRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/about': {
      id: '/dashboard/_layout/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardLayoutAboutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/client/_clientLayout/dashboard': {
      id: '/client/_clientLayout/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientClientLayoutDashboardRouteRouteImport
      parentRoute: typeof ClientClientLayoutRouteRoute
    }
    '/admin/_adminLayout/search': {
      id: '/admin/_adminLayout/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminAdminLayoutSearchRouteRouteImport
      parentRoute: typeof AdminAdminLayoutRouteRoute
    }
    '/admin/_adminLayout/dashboard': {
      id: '/admin/_adminLayout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminLayoutDashboardRouteRouteImport
      parentRoute: typeof AdminAdminLayoutRouteRoute
    }
    '/admin/_adminLayout/categories': {
      id: '/admin/_adminLayout/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminLayoutCategoriesRouteRouteImport
      parentRoute: typeof AdminAdminLayoutRouteRoute
    }
    '/client/_clientLayout/contact-us/': {
      id: '/client/_clientLayout/contact-us/'
      path: '/contact-us'
      fullPath: '/client/contact-us/'
      preLoaderRoute: typeof ClientClientLayoutContactUsIndexRouteImport
      parentRoute: typeof ClientClientLayoutRouteRoute
    }
    '/client/_clientLayout/contact-us/$country': {
      id: '/client/_clientLayout/contact-us/$country'
      path: '/contact-us/$country'
      fullPath: '/client/contact-us/$country'
      preLoaderRoute: typeof ClientClientLayoutContactUsCountryRouteImport
      parentRoute: typeof ClientClientLayoutRouteRoute
    }
    '/admin/_adminLayout/categories/$categoryId': {
      id: '/admin/_adminLayout/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AdminAdminLayoutCategoriesCategoryIdRouteRouteImport
      parentRoute: typeof AdminAdminLayoutCategoriesRouteRoute
    }
    '/(public)/app/users/$userId': {
      id: '/(public)/app/users/$userId'
      path: '/app/users/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof publicAppUsersUserIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/_clientLayout/contact-us/$country/$city': {
      id: '/client/_clientLayout/contact-us/$country/$city'
      path: '/$city'
      fullPath: '/client/contact-us/$country/$city'
      preLoaderRoute: typeof ClientClientLayoutContactUsCountryCityRouteImport
      parentRoute: typeof ClientClientLayoutContactUsCountryRoute
    }
    '/(public)/app/users/$userId/setting': {
      id: '/(public)/app/users/$userId/setting'
      path: '/setting'
      fullPath: '/app/users/$userId/setting'
      preLoaderRoute: typeof publicAppUsersUserIdSettingRouteImport
      parentRoute: typeof publicAppUsersUserIdRouteRoute
    }
    '/(public)/app/users/$userId/edit': {
      id: '/(public)/app/users/$userId/edit'
      path: '/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof publicAppUsersUserIdEditRouteImport
      parentRoute: typeof publicAppUsersUserIdRouteRoute
    }
    '/admin/_adminLayout/categories/$categoryId/$subcategoryId': {
      id: '/admin/_adminLayout/categories/$categoryId/$subcategoryId'
      path: '/$subcategoryId'
      fullPath: '/admin/categories/$categoryId/$subcategoryId'
      preLoaderRoute: typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteImport
      parentRoute: typeof AdminAdminLayoutCategoriesCategoryIdRouteRoute
    }
    '/admin/_adminLayout/app/users/$userId': {
      id: '/admin/_adminLayout/app/users/$userId'
      path: '/app/users/$userId'
      fullPath: '/admin/app/users/$userId'
      preLoaderRoute: typeof AdminAdminLayoutAppUsersUserIdRouteRouteImport
      parentRoute: typeof AdminAdminLayoutRouteRoute
    }
    '/admin/_adminLayout/app/users/$userId/setting': {
      id: '/admin/_adminLayout/app/users/$userId/setting'
      path: '/setting'
      fullPath: '/admin/app/users/$userId/setting'
      preLoaderRoute: typeof AdminAdminLayoutAppUsersUserIdSettingRouteImport
      parentRoute: typeof AdminAdminLayoutAppUsersUserIdRouteRoute
    }
    '/admin/_adminLayout/app/users/$userId/edit': {
      id: '/admin/_adminLayout/app/users/$userId/edit'
      path: '/edit'
      fullPath: '/admin/app/users/$userId/edit'
      preLoaderRoute: typeof AdminAdminLayoutAppUsersUserIdEditRouteImport
      parentRoute: typeof AdminAdminLayoutAppUsersUserIdRouteRoute
    }
    '/admin/_adminLayout/categories/$categoryId/$subcategoryId/$productId': {
      id: '/admin/_adminLayout/categories/$categoryId/$subcategoryId/$productId'
      path: '/$productId'
      fullPath: '/admin/categories/$categoryId/$subcategoryId/$productId'
      preLoaderRoute: typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport
      parentRoute: typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRoute
    }
  }
}

interface AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteChildren {
  AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute: typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
}

const AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteChildren: AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteChildren =
  {
    AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute:
      AdminAdminLayoutCategoriesCategoryIdSubcategoryIdProductIdRouteRoute,
  }

const AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren =
  AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRoute._addFileChildren(
    AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteChildren,
  )

interface AdminAdminLayoutCategoriesCategoryIdRouteRouteChildren {
  AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRoute: typeof AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
}

const AdminAdminLayoutCategoriesCategoryIdRouteRouteChildren: AdminAdminLayoutCategoriesCategoryIdRouteRouteChildren =
  {
    AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRoute:
      AdminAdminLayoutCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren,
  }

const AdminAdminLayoutCategoriesCategoryIdRouteRouteWithChildren =
  AdminAdminLayoutCategoriesCategoryIdRouteRoute._addFileChildren(
    AdminAdminLayoutCategoriesCategoryIdRouteRouteChildren,
  )

interface AdminAdminLayoutCategoriesRouteRouteChildren {
  AdminAdminLayoutCategoriesCategoryIdRouteRoute: typeof AdminAdminLayoutCategoriesCategoryIdRouteRouteWithChildren
}

const AdminAdminLayoutCategoriesRouteRouteChildren: AdminAdminLayoutCategoriesRouteRouteChildren =
  {
    AdminAdminLayoutCategoriesCategoryIdRouteRoute:
      AdminAdminLayoutCategoriesCategoryIdRouteRouteWithChildren,
  }

const AdminAdminLayoutCategoriesRouteRouteWithChildren =
  AdminAdminLayoutCategoriesRouteRoute._addFileChildren(
    AdminAdminLayoutCategoriesRouteRouteChildren,
  )

interface AdminAdminLayoutAppUsersUserIdRouteRouteChildren {
  AdminAdminLayoutAppUsersUserIdEditRoute: typeof AdminAdminLayoutAppUsersUserIdEditRoute
  AdminAdminLayoutAppUsersUserIdSettingRoute: typeof AdminAdminLayoutAppUsersUserIdSettingRoute
}

const AdminAdminLayoutAppUsersUserIdRouteRouteChildren: AdminAdminLayoutAppUsersUserIdRouteRouteChildren =
  {
    AdminAdminLayoutAppUsersUserIdEditRoute:
      AdminAdminLayoutAppUsersUserIdEditRoute,
    AdminAdminLayoutAppUsersUserIdSettingRoute:
      AdminAdminLayoutAppUsersUserIdSettingRoute,
  }

const AdminAdminLayoutAppUsersUserIdRouteRouteWithChildren =
  AdminAdminLayoutAppUsersUserIdRouteRoute._addFileChildren(
    AdminAdminLayoutAppUsersUserIdRouteRouteChildren,
  )

interface AdminAdminLayoutRouteRouteChildren {
  AdminAdminLayoutCategoriesRouteRoute: typeof AdminAdminLayoutCategoriesRouteRouteWithChildren
  AdminAdminLayoutDashboardRouteRoute: typeof AdminAdminLayoutDashboardRouteRoute
  AdminAdminLayoutSearchRouteRoute: typeof AdminAdminLayoutSearchRouteRoute
  AdminAdminLayoutAppUsersUserIdRouteRoute: typeof AdminAdminLayoutAppUsersUserIdRouteRouteWithChildren
}

const AdminAdminLayoutRouteRouteChildren: AdminAdminLayoutRouteRouteChildren = {
  AdminAdminLayoutCategoriesRouteRoute:
    AdminAdminLayoutCategoriesRouteRouteWithChildren,
  AdminAdminLayoutDashboardRouteRoute: AdminAdminLayoutDashboardRouteRoute,
  AdminAdminLayoutSearchRouteRoute: AdminAdminLayoutSearchRouteRoute,
  AdminAdminLayoutAppUsersUserIdRouteRoute:
    AdminAdminLayoutAppUsersUserIdRouteRouteWithChildren,
}

const AdminAdminLayoutRouteRouteWithChildren =
  AdminAdminLayoutRouteRoute._addFileChildren(
    AdminAdminLayoutRouteRouteChildren,
  )

interface ClientClientLayoutContactUsCountryRouteChildren {
  ClientClientLayoutContactUsCountryCityRoute: typeof ClientClientLayoutContactUsCountryCityRoute
}

const ClientClientLayoutContactUsCountryRouteChildren: ClientClientLayoutContactUsCountryRouteChildren =
  {
    ClientClientLayoutContactUsCountryCityRoute:
      ClientClientLayoutContactUsCountryCityRoute,
  }

const ClientClientLayoutContactUsCountryRouteWithChildren =
  ClientClientLayoutContactUsCountryRoute._addFileChildren(
    ClientClientLayoutContactUsCountryRouteChildren,
  )

interface ClientClientLayoutRouteRouteChildren {
  ClientClientLayoutDashboardRouteRoute: typeof ClientClientLayoutDashboardRouteRoute
  ClientClientLayoutContactUsCountryRoute: typeof ClientClientLayoutContactUsCountryRouteWithChildren
  ClientClientLayoutContactUsIndexRoute: typeof ClientClientLayoutContactUsIndexRoute
}

const ClientClientLayoutRouteRouteChildren: ClientClientLayoutRouteRouteChildren =
  {
    ClientClientLayoutDashboardRouteRoute:
      ClientClientLayoutDashboardRouteRoute,
    ClientClientLayoutContactUsCountryRoute:
      ClientClientLayoutContactUsCountryRouteWithChildren,
    ClientClientLayoutContactUsIndexRoute:
      ClientClientLayoutContactUsIndexRoute,
  }

const ClientClientLayoutRouteRouteWithChildren =
  ClientClientLayoutRouteRoute._addFileChildren(
    ClientClientLayoutRouteRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutAboutRoute: typeof DashboardLayoutAboutRoute
  DashboardLayoutSettingRoute: typeof DashboardLayoutSettingRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutAboutRoute: DashboardLayoutAboutRoute,
  DashboardLayoutSettingRoute: DashboardLayoutSettingRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface publicAppUsersUserIdRouteRouteChildren {
  publicAppUsersUserIdEditRoute: typeof publicAppUsersUserIdEditRoute
  publicAppUsersUserIdSettingRoute: typeof publicAppUsersUserIdSettingRoute
}

const publicAppUsersUserIdRouteRouteChildren: publicAppUsersUserIdRouteRouteChildren =
  {
    publicAppUsersUserIdEditRoute: publicAppUsersUserIdEditRoute,
    publicAppUsersUserIdSettingRoute: publicAppUsersUserIdSettingRoute,
  }

const publicAppUsersUserIdRouteRouteWithChildren =
  publicAppUsersUserIdRouteRoute._addFileChildren(
    publicAppUsersUserIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAdminLayoutRouteRoute: AdminAdminLayoutRouteRouteWithChildren,
  ClientClientLayoutRouteRoute: ClientClientLayoutRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DisplayDisplayRoute: DisplayDisplayRoute,
  publicAppUsersUserIdRouteRoute: publicAppUsersUserIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
